import type { ReactNode } from "react";
import { AIModulesPage } from "../pages/AIModulesPage";
import { CamerasPage } from "../pages/CamerasPage";
import { DashboardPage } from "../pages/DashboardPage";
import { DetectPage } from "../pages/DetectPage";
import { LiveViewPage } from "../pages/LiveViewPage";
import { PlaceholderPage } from "../pages/PlaceholderPage";
import { SettingsPage } from "../pages/SettingsPage";

export interface AppRoute {
  path: string;
  navLabel: string;
  element: ReactNode;
}

/** Single source of truth for the sidebar and the router: every entry here appears in both. */
export const APP_ROUTES: AppRoute[] = [
  { path: "/", navLabel: "Dashboard", element: <DashboardPage /> },
  { path: "/detect", navLabel: "Detect (prototype)", element: <DetectPage /> },
  { path: "/cameras", navLabel: "Cameras", element: <CamerasPage /> },
  { path: "/live-view", navLabel: "Live View", element: <LiveViewPage /> },
  {
    path: "/events",
    navLabel: "Events",
    element: (
      <PlaceholderPage
        title="Events"
        description="Browse structured events generated by AI modules (entries/exits, zone activity, OCR reads, and more)."
        phase="Phase 9 (Events + analytics system)"
      />
    ),
  },
  {
    path: "/analytics",
    navLabel: "Analytics",
    element: (
      <PlaceholderPage
        title="Analytics"
        description="Historical charts and reports: people counts, entry/exit trends, heatmaps, vehicle counts."
        phase="Phase 9 (Events + analytics system)"
      />
    ),
  },
  { path: "/ai-modules", navLabel: "AI Modules", element: <AIModulesPage /> },
  { path: "/settings", navLabel: "Settings", element: <SettingsPage /> },
  {
    path: "/account",
    navLabel: "Account",
    element: (
      <PlaceholderPage
        title="Account"
        description="Sign in, manage your organization and locations."
        phase="Phase 10 (Authentication + organizations + locations)"
      />
    ),
  },
  {
    path: "/subscription",
    navLabel: "Subscription",
    element: (
      <PlaceholderPage
        title="Subscription"
        description="Trial status, plan (Own Hardware or Vero Cloud), and billing via PayPal."
        phase="Phase 11 (trial/licensing) and Phase 15 (PayPal integration)"
      />
    ),
  },
];
