"""create events and heatmap_snapshots tables

Revision ID: 50baef6ef6b0
Revises: adf6d7f495a8
Create Date: 2026-09-21 23:23:37.309947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50baef6ef6b0'
down_revision: Union[str, Sequence[str], None] = 'adf6d7f495a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_camera_time', 'events', ['camera_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_type_time', 'events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('heatmap_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_width', sa.Integer(), nullable=False),
    sa.Column('frame_height', sa.Integer(), nullable=False),
    sa.Column('grid_width', sa.Integer(), nullable=False),
    sa.Column('grid_height', sa.Integer(), nullable=False),
    sa.Column('cells', sa.LargeBinary(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'period_start', 'grid_width', 'grid_height', name='uq_heatmap_camera_hour_grid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heatmap_snapshots')
    op.drop_index('ix_events_type_time', table_name='events')
    op.drop_index('ix_events_camera_time', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
