"""create subscriptions table

Revision ID: 7fb7b8f91aea
Revises: 267eb54642fb
Create Date: 2026-09-23 18:56:49.594078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb7b8f91aea'
down_revision: Union[str, Sequence[str], None] = '267eb54642fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='trialing', nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_cameras', sa.Integer(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    # ### end Alembic commands ###

    # Backfill: every organization that predates this migration (created during Phase 10)
    # gets a subscription too. A *fresh* 3-day trial starting now, not backdated to the
    # organization's own created_at — otherwise anyone who registered more than 3 days ago
    # would find themselves instantly "expired" the moment this ships.
    op.execute(
        """
        INSERT INTO subscriptions (id, organization_id, status, trial_started_at, trial_ends_at, created_at, updated_at)
        SELECT gen_random_uuid(), id, 'trialing', now(), now() + interval '3 days', now(), now()
        FROM organizations
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
