"""create cameras table

Revision ID: 9659ecac8d54
Revises: 42dad291e541
Create Date: 2026-09-19 21:31:44.853664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9659ecac8d54'
down_revision: Union[str, Sequence[str], None] = '42dad291e541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rtsp_url', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('location_label', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('connection_status', sa.String(length=16), server_default='unknown', nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_fps', sa.Float(), nullable=True),
    sa.Column('last_width', sa.Integer(), nullable=True),
    sa.Column('last_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cameras')
    # ### end Alembic commands ###
