"""add cameras enabled_modules

Revision ID: adf6d7f495a8
Revises: 4c662e136795
Create Date: 2026-09-21 22:09:31.200986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adf6d7f495a8'
down_revision: Union[str, Sequence[str], None] = '4c662e136795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('enabled_modules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["people"]\'::jsonb'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'enabled_modules')
    # ### end Alembic commands ###
