<#
.SYNOPSIS
Phase 16: called from NSIS_HOOK_POSTINSTALL. Generates the packaged backend's config
file on a genuinely first install, and deliberately leaves it untouched on a reinstall/
upgrade (losing CAMERA_CREDENTIALS_KEY makes every stored camera password permanently
unrecoverable; losing AUTH_SECRET_KEY signs every account out - see backend/app/config.py's
own comments on these values).

Writes C:\ProgramData\Vero.ai\config.env - the file backend/app/config.py reads via
VERO_CONFIG_PATH (set on the "VeroAiBackend" service's environment by the NSSM
registration in hooks.nsi), never the repo-root .env dev/tests use.

Uses RNGCryptoServiceProvider, not [System.Security.Cryptography.RandomNumberGenerator]::Fill
- the latter doesn't exist under Windows PowerShell 5.1 (the .NET Framework runtime NSIS's
bundled PowerShell actually runs) and silently produces all-zero bytes there instead of
throwing, which would ship every install with predictable, effectively-known secrets.
Confirmed by direct testing, not assumed.
#>
$ErrorActionPreference = "Stop"

$ConfigDir = "C:\ProgramData\Vero.ai"
$ConfigPath = Join-Path $ConfigDir "config.env"
$PgDataDir = Join-Path $ConfigDir "pgdata"

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

if (Test-Path $ConfigPath) {
    Write-Host "$ConfigPath already exists (reinstall/upgrade) - leaving it untouched."
    exit 0
}

$Rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()

function New-RandomToken([int]$Bytes = 36) {
    $buffer = New-Object byte[] $Bytes
    $Rng.GetBytes($buffer)
    return [Convert]::ToBase64String($buffer).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function New-FernetKey() {
    # Fernet keys are exactly 32 raw bytes, url-safe base64 encoded WITH padding kept -
    # matches cryptography.fernet.Fernet.generate_key()'s own format exactly (verified
    # against a real Fernet(...) round-trip, not just format inspection).
    $buffer = New-Object byte[] 32
    $Rng.GetBytes($buffer)
    return [Convert]::ToBase64String($buffer).Replace('+', '-').Replace('/', '_')
}

$cameraCredentialsKey = New-FernetKey
$authSecretKey = New-RandomToken -Bytes 48
$postgresPassword = New-RandomToken -Bytes 24

# 5432 is Postgres's default, but a customer's machine may already have something else
# on it (this dev machine does, from an unrelated project) - probe before committing to
# it rather than generating a config the bundled Postgres can't actually bind to.
function Test-PortFree([int]$Port) {
    $listener = $null
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        return $true
    } catch {
        return $false
    } finally {
        if ($listener) { $listener.Stop() }
    }
}

$postgresPort = 5432
while (-not (Test-PortFree -Port $postgresPort)) {
    Write-Host "Port $postgresPort is already in use on this machine - trying the next one."
    $postgresPort++
}
Write-Host "Bundled PostgreSQL will listen on 127.0.0.1:$postgresPort"

$databaseUrl = "postgresql+psycopg://vero:$postgresPassword@127.0.0.1:$postgresPort/vero"

@"
# Generated by packaging/generate_first_run_config.ps1 on first install. Do not edit the
# secrets below by hand - regenerating them makes existing stored data unusable (see the
# comments in backend/app/config.py and backend/app/crypto.py).
DATABASE_URL=$databaseUrl
CAMERA_CREDENTIALS_KEY=$cameraCredentialsKey
AUTH_SECRET_KEY=$authSecretKey
VERO_POSTGRES_PASSWORD=$postgresPassword
VERO_POSTGRES_PORT=$postgresPort
"@ | Set-Content -Path $ConfigPath -Encoding utf8

Write-Host "Wrote $ConfigPath"

if (-not (Test-Path $PgDataDir)) {
    Write-Host "$PgDataDir does not exist yet - initdb runs separately (see hooks.nsi)."
}
